config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  
  devise_for :users, :path => 'accounts'

  post 'createfollowship/:from_user/:to_user', to: 'followships#create_followship', as: "create_followship"
  delete 'deletefollowship/:from_user/:to_user', to: 'followships#destroy_followship', as: "destroy_followship"

  resources :users, :only => [:index, :show] do
    resources :tweets, :only => [:show, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/followship.rb
class Followship < ApplicationRecord
  belongs_to :follower, class_name: :User
  belongs_to :following, class_name: :User
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :tweet, length: {minimum: 1, maximum: 280}, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy
  has_many :passive_followships, class_name: "Followship", 
                                 foreign_key: "following_id",
                                 dependent: :destroy
  has_many :followers, through: :passive_followships
  has_many :active_followships, class_name: "Followship", 
                                 foreign_key: "follower_id",
                                 dependent: :destroy
  has_many :followings, through: :active_followships
  has_one_attached :avatar
  validates :name, :username, :email, presence: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :email, :password, :avatar])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :email, :password, :current_password, :avatar])
    end
end

app/controllers/followships_controller.rb
class FollowshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_follower
  before_action :set_following

  def create_followship
    if !@follower_user.followings.include?(@following_user)
      @follower_user.followings << @following_user
      redirect_to @follower_user
    end
  end

  def destroy_followship
    if @follower_user.followings.include?(@following_user)
      @follower_user.followings.delete(@following_user)
      redirect_to @follower_user
    end
  end

  private

  def set_follower
    @follower_user = User.find(params[:from_user])
  end

  def set_following
    @following_user = User.find(params[:to_user])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
before_action :authenticate_user!

  # home page
  def home
    @feed = Array.new
    current_user.followings.each do |following| 
      following.tweets.each do |tweet|
        @feed << tweet
      end
    end
    current_user.tweets.each do |tweet|
      @feed << tweet
    end
    @feed.compact
    @tweet = current_user.tweets.build
    @feed.sort_by! { |tweet| tweet.created_at }
    @feed.reverse!
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: [:show, :destroy]

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @user = current_user
    @tweet = @user.tweets.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to '/', notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { redirect_to '/' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :tweet)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @tweets = @user.tweets.order("created_at DESC")
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :username, :email, :avatar)
    end

    def check_user
      if @user != current_user
        redirect_to users_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <p class="alert"><%= notice %></p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <p class="alert"><%= alert %></p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <nav class="navbar navbar-expand-sm navbar-light mb-4" style="background-color: #e3f2fd;">
      <div class="container">
        <%= link_to 'Twitter', "/", class: 'navbar-brand' %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <!-- Should only be seen if logged in-->
              <% if user_signed_in? %>
                <li class="nav-item"><%= link_to 'People', "/users", method: :get, class: 'nav-link active' %></li>
                <li class="nav-item"><%= link_to 'Profile', "/users/#{current_user.id}", method: :get, class: "nav-link active" %></li>
                <li class="nav-item"><%= button_to 'Log Out', '/accounts/sign_out', method: :delete, class: "btn btn-primary" %></li>
            <!-- Should only be seen if NOT logged in -->
              <% else %>
                <li class="nav-item"><%= button_to 'Log In', '/accounts/sign_in', method: :get, class: "btn btn-outline-primary" %></li>
                <li class="nav-item"><%= button_to 'Sign Up', "/accounts/sign_up", method: :get, class: "btn btn-primary" %></li>
              <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<div class="card border-primary mb-3">
  <div class="card-body">
    <%= form_with(model: [tweet.user, tweet], local: true) do |form| %>
      <% if tweet.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>
          <ul>
            <% tweet.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= link_to user_path(tweet.user) do %>
        <% if tweet.user.avatar.attached? %>
            <img class="non-profile-pic" src="<%= url_for(tweet.user.avatar) %>%"/>
        <% else %>
            <%= image_tag("avatar.jpg", class:"non-profile-pic") %>
        <% end %>
      <% end %>

      <div class="field form-group">
        <%= form.text_area :tweet, class: "form-control" %>
      </div>

      <div class="actions">
        <%= form.submit "Tweet", class: 'btn btn-primary float-right'%>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="section">
  <div class="container">
    <h2 class="page-title">Home</h2>
      <%= render 'form', tweet: @tweet %>

      <table class="table table-hover">
        <tbody>
        <% if !@feed.empty? %>
          <% @feed.each do |tweet| %>
            <tr>
              <td>
                <%= link_to user_tweet_path(tweet.user, tweet) do %>
                <% if tweet.user.avatar.attached? %>
                  <img class="non-profile-pic" src="<%= url_for(tweet.user.avatar) %>%"/>
                <% else %>
                  <%= image_tag("avatar.jpg", class:"non-profile-pic") %>
                <% end %>
                <p class="tweet-display-name-same-row"><%= tweet.user.name%></p>
                <p class="tweet-display-username-same-row">@<%= tweet.user.username %></p>
                <p><%= tweet.tweet %></p>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <p class="page-title">Create a New Tweet or Follow Someone</p>
        <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="section">
  <div class="container">
    <h2 class="page-title">Tweet</h2>
    <div class="card border-primary mb-3">
      <div class="card-body">
        <% if @tweet.user.avatar.attached? %>
          <%= link_to user_path(@tweet.user) do %>
            <img class="non-profile-pic" src="<%= url_for(@tweet.user.avatar) %>%"/>
          <% end %>
        <% else %>
          <%= link_to user_path(@tweet.user) do %>
            <%= image_tag("avatar.jpg", class:"non-profile-pic" )%>
          <% end %>
        <% end %>
        <p class="tweet-display-name-same-row"><%= @tweet.user.name%></p>
        <p class="tweet-display-username-same-row">@<%= @tweet.user.username %></p>
        <p><%= @tweet.tweet %></p>
        <p><%= @tweet.created_at %></p>
        <% if @tweet.user == current_user %>
            <td><%= link_to 'Delete', user_tweet_path(@tweet.user, @tweet), method: :delete, data: { confirm: 'Are you sure?' }, class: "card-link" %></td>
        <% end %>
      </div>
    </div>
    <%= link_to 'Back', url_for(:back), class: "nav-link" %>
  </div>
</div>

app/views/users/index.html.erb
<div class="section">
  <div class="container">
    <h2 class="page-title">People</h2>
    <table class="table" style ="margin-top: 10px;">
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to user_path(user) do %>
                <% if user.avatar.attached? %>
                    <img class= "non-profile-pic" src="<%= url_for(user.avatar) %>%"/>
                <% else %>
                    <%= image_tag("avatar.jpg", class:"non-profile-pic") %>
                <% end %>
              <% end %>
              <%= link_to user_path(user) do %>
                <p style="margin-bottom: 0px;"><b><%= user.name %></b></p>
              <% end %>
              <p>@<%= user.username %></p>
            </td>
            <td>
              <% if user != current_user %>
                <% if current_user.followings.include?(user)%>
                  <%= button_to 'Following', user_path(user), method: :get, class: "btn btn-primary" %>
                <% else %>
                  <%= button_to 'Follow', user_path(user), method: :get, class: "btn btn-outline-primary" %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="section">
  <div class="container">
    <h2 class="page-title"><%= @user.name %></h2>
    <div class="card border-primary mb-3">
      <div class="card-body">
        <% if @user.avatar.attached? %>
            <img class="profile-pic" src="<%= url_for(@user.avatar) %>%"/>
        <% else %>
            <%= image_tag("avatar.jpg", class:"profile-pic") %>
        <% end %>
        <p style="margin-bottom: 0px;"><strong><%= @user.name%></strong></p>
        <p style="margin-bottom: 0px;">@<%= @user.username %></p>
        <p style="margin-bottom: 5px;"><%= @user.email %></p>
        <p>Joined <%= @user.created_at %></p>
        <p><strong><%= @user.followings.count %></strong> Following</p>
        <p><strong><%= @user.followers.count %></strong> Followers</p>
        <% if @user == current_user %>
          <%= button_to 'Edit Profile', '/accounts/edit', method: :get, class: "btn btn-outline-primary"%>
        <% else %>
          <% if current_user.followings.include?(@user)%>
              <%= button_to 'Unfollow', "/deletefollowship/#{current_user.id}/#{@user.id}", method: :delete, class: 'btn btn-danger' %>
          <% else %>
              <%= button_to 'Follow', "/createfollowship/#{current_user.id}/#{@user.id}", method: :post, class: "btn btn-outline-primary"%>
          <% end %>
        <% end %>
          </div>
        </div>

      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Tweets</th>
          </tr>
        </thead>
        <tbody>
          <% @tweets.each do |tweet| %>
            <tr>
              <td>
                <%= link_to user_tweet_path(@user, tweet) do %>
                <% if @user.avatar.attached? %>
                  <img class="non-profile-pic" src="<%= url_for(@user.avatar) %>%"/>
                <% else %>
                  <%= image_tag("avatar.jpg", class:"non-profile-pic") %>
                <% end %>
                <p class="tweet-display-name-same-row"><%= @user.name%></p>
                <p class="tweet-display-username-same-row">@<%= @user.username %></p>
                <p><%= tweet.tweet %></p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <%= link_to 'Back', url_for(:back), class: "nav-link" %>
  </div>
</div>